[pytest]
testpaths =
    web_automation/tests_web
    mobile_automation/tests_mobile
    api

addopts = --alluredir=allure-results -s -v

markers =
    web: testes de automação web
    mobile: testes de automação mobile
    api: testes que envolvem requisições para a API
    order: define ordem de execução dos testes

log_cli = true
log_cli_level = INFO
log_format = %(asctime)s - %(levelname)s - %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
